### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by HarryHeights** [ramack/ActivityDiary#193]
Hello, I'm Harry. I contribute to open source software by creating documents I think might be necessary. I'd love to create a privacy policy document for Activity Diary. However if it's not needed and there are other documentation work you might need. I'll be at your beck and call.

**Comment by ramack** [comment]
Sounds good. For a privacy policy document I am not sure whether we need it. At least until we have some "cloud-features". More helpful would be to create some basic documentation, probably best in the wiki here on github, and what is always welcome would be to create new screenshots for new releases, best with different languages.

**Comment by ramack** [comment]
Hello @HarryHeights, sorry for the long time until I respond, but I am quite offline the last (and upcoming) time due to vacation and some high prio personal topics.

Still I am very interested in your help.
I mainly though about extending the "User Manual" on https://github.com/ramack/ActivityDiary/wiki/Usage to help people to get started with ActivityDiary and describe how the app can be used. Already the screenshot is quite ancient there. There a re a few things already mentioned what should be added, but maybe we need much more and probably a reasonable structuring would be helpful. Having all in one page doesn't look like the good long-term solution.
Here, the best solution would be if you could just file a pull request against the markdown files in the wiki repository.

But also if you want to post a short introduction on a blog this would help. If you want I can review it before publishing.

**Comment by HarryHeights** [comment]
Alright. Thanks for your reply.
I'll see if I can work something. I just read through the usage on the wiki. Problem I have is I have never worked on a wiki on Github. I really don't know how it's done. I mostly just create a new file on the code tab and make a pull request.

**Comment by ramack** [comment]
There is a separate git repo for the wiki: https://github.com/ramack/ActivityDiary.wiki.git which you can clone and change/add markdown files. For this you should also be able to create a PR. But also a PR with a markdown file for the usage ibid the main repo will be useful and I'll try to move it afterwards...

**Comment by HarryHeights** [comment]
Okay. I'll try to to work on the wiki, if I'm not able to, I'll create a PR
on the main repo and yes it'll be in markdown. I'm quite conversant with
markdown.

**Comment by ramack** [comment]
Hello @HarryHeights,

what about your plans to help with documentation for ActivityDiary? It would be great to read from you. Any help is welcome.

In the meantime I added a privacy policy by the way, so if you have experience a review would not harm... But also documentation is always good to have.

**Comment by HarryHeights** [comment]
Whoa!!! It's been 5 months. Time really flew.
