### ISSUE TITLE
Statistics: configurable formatting of duration?

### ISSUE THREAD

**Issue by dennisguse** [ramack/ActivityDiary#212]
In the _statistics section_, the duration is shown as days, hours, minutes, and seconds.
For my purpose this is, however, quite hard to read (I track my work duration).

Thus, I would prefer to format get the duration formatted in hours and minutes only.
Otherwise it is quite hard to read...

![screenshot_20180924-071434](https://user-images.githubusercontent.com/2820825/45938384-b3c27f00-bfc9-11e8-8706-793a51daef59.png)

It would be great if the formatting of the duration in the statistics section would be configurable.

**Comment by ramack** [comment]
this is true. What about selecting the format dynamically?
```
if duration > 5 day (120 h)
   days
else if duration > 5 day (120 h)
   days:hours
else if duration > 1.5 day
   days:hours:min
else if duration > 1.5 hours
   hours:min
else if duration > 1.5 minutes
   min:sec
else
   sec
```
this should already simplify the view. But maybe your use case is not yet covered, because you probably would like to stay with hours and never show days, right?

Another use case for showing days is to allow logging things like "vacation in France" as a "several days long" period, which would not be meaningful to give in hours:min.

And the situation is even worse... there are two other, different time format shortening variants in the "currently active activity" and in the history view, where a user might even be interested in exact details.

So maybe the best would be a setting with options
- "use default short format" (as described above)
- "never use days, stay with hours also for longer times"
- "long format wiht days", not hiding min and seconds even for long periods
- "long format without day shortening"

This option should affect all three places: statistics, history and current time.

What do you think?

**Comment by dennisguse** [comment]
Sounds good.
However, I don't know how many people track multi-day activities..

What do you think about the following names:
* "dynamic: adjust format depending on duration"
* "full: use days, hours, minutes, and seconds"
* "hours or less: use only hours, minutes, and seconds"
* "days and hours: only show days and hours"
* "days: only show days"

PS: I interpreted the last two cases :)

**Comment by ramack** [comment]
Somehow I don't like the characters for denoting hour, minutes, and seconds. What do you think about using primes for min and sec in durations? like 1d 7h 14' 25''?

Right now I prefer the list
- "dynamic: adjust format depending on duration"
- "precise: use days, hours, minutes, and seconds" (renamed, because I still want to cut leading 0's)
- "hours or less: use only hours, minutes, and seconds"
- "hours and minutes: don't show days and seconds"

your last two are probably not needed specifically but only in dyanmic.
