### ISSUE TITLE
Notifications too loud

### ISSUE THREAD

**Issue by ramack** [ramack/ActivityDiary#214]
Currently the notification update for the duration generates a beep and a vibration, if configured. This is too intrusive for only the update od the duration. check if this could be updated without Renotification...

**Comment by vit1-irk** [comment]
If you will remove "renotification", please add an option to the settings to revert this behaviour back

I liked your app because repeating notifications help me to avoid procrastinating things. System notifications are synced over KDEConnect to the desktop computer, so it helps to stay focused and not get distracted

I didn't see any other apps providing such a useful feature

**Comment by ramack** [comment]
Currently the renotifications are not really deterministic in terms of time, as it is mainly driven by reevaluation of the likely next activities, so maybe it would be best to put this into a clear feature.

The current notification is probably best updated with the option to alert the user only once and then, if configured to do a cyclic re-alert every <configurable> minutes. Would that fit your needs?

**Comment by vit1-irk** [comment]
Cyclic re-alert (or notification text update) is exactly what needed. I mean, it is already "working", but if you need to improve the code, the feature is to be implemented explicitly.
