### ISSUE TITLE
Release cycle?

### ISSUE THREAD

**Issue by dennisguse** [ramack/ActivityDiary#237]
At the moment, I use ActivityDiary via Fdroid (as I am too lazy too manually compile at the moment).

For me, it would be great to tag more releases, so it will be available via Fdroid.
to avoid issues with regular users, the version could be tagged as "-alpha".

That's how Fdroid is shipping their testing version: https://f-droid.org/en/packages/org.fdroid.fdroid/

**Comment by ramack** [comment]
I know, the next release is long overdue, mainly because I did not have a lot of time to work on it ;-(

Using the specific tags to have later releases built but not automatically updated (as f-droid client) requires manual effort to push the pre-release to f-droid. I am not so happy with that.

Additionally unstable versions are somehow "dangerous", so I am not sure whether users want to work on their "real" data to test new versions, so somehow I would tend to publish pre-releases with a different package name, such that both can be installed together and operate on a different database.

But I also understand your request. Maybe the best would be to have both: "alpha" version in a seperate package name for first testing and "beta" in the same to be able to upgrade manually to the more stable but not yet fully translated and finally released stuff...

Also the question comes up which features and bug fixes should be done in which order and which release?

Until the dev team grows and we find volunteers to support here I propose to try to reduce the size of the milestones to get them released faster. Would that be fine?

**Comment by dennisguse** [comment]
No pressure :)
Sounds awesome!
