### ISSUE TITLE
How to delete entries ?

### ISSUE THREAD

**Issue by alm10965** [ramack/ActivityDiary#266]
Hello, I'm testing this app for my use. My first problem is, that I can't find a way to delete aktivity entries.

**Comment by ramack** [comment]
Sorry for the inconvenience, but deleting is not yet implemented. As usually in free software contributions are warmly welcome. In case you don't know how to code and don't want to learn it (for sure I will support if you are interested) you still have the possibility to pay someone to implement missing features...

closing, since duplicate (#28).
