### ISSUE TITLE
Can an improvement be possible?

### ISSUE THREAD

**Issue by jaepo10** [ramack/ActivityDiary#272]
Hi. Sometimes I remember writing down an activity some time after it started. What improvement could help in these cases.  Could it be the expected start and end time assignment?' I'm new here and this message was composed with the help of the online translator deepl.com

**Comment by ramack** [comment]
welcome! I have the same issue, that I often forget to change the activity. Usually I go to the history and modify the start time there. In the long term I want to simplify this kind of "late switching", e. g. in the snackbar appearing after the change of the activity (where you can do the UNDO) and allow there to select "I was late" which can open a dialog to ask how long the activity is already going (or since when). This is what is described in #137 - I still plan to do that, but these days I don't have much time to work on ActivityDiary. Contributions are welcome!

I hope it is ok for you if I close this ticket in favor of #137. If you mean something else, feel free to explain and reopen it.
