### ISSUE TITLE
Add option to delete past activities - by direct interation

### ISSUE THREAD

**Issue by Mmedic23** [ramack/ActivityDiary#79]

**Comment by Mmedic23** [comment]
I accidentally pressed the post button without adding a description, but it's pretty much self explanatory. Option go edit past activities would be good for accidental clicks or change of mind etc. I don't know if it's been proposed before but it seems like an essential feature to me.

**Comment by ramack** [comment]
Thanks for reporting. I fully agree with this. Partly this is covered by #28, by adding more possibilities to change the history. But as I read it from you there is a second aspect that should be covered special:

When the wrong activity was selected due to touching (or even without an intention to change the activity at all) there should be a fast and easy way to undo the selection. I could imagine a snackbar (the box coming in from the lower edge of the screen) telling that the activity was changed to "xxx" with an "undo" button. With that the user would have the chance to directly correct a mis-selection.

Alternatively we could automatically remove short activities - where short is configurable, with a default of 5 sec? Then you could just do the correction and the wrong activity would not show up in the diary. Or - as the data storage doesn't cost anything - just hide the short entries in the diary and do not consider them in evaluations.

Maybe we could also add an entry in the action bar menu, or allow to change the current activity by touching the "current activity" in the top of the main view, instead of editing it?

What do you think is best?

**Comment by Mmedic23** [comment]
I feel like all the ideas you proposed are great to be honest.

The snackbar option seems very useful and a solid solution to mis-selects. Some users could find it annoying, but I'm sure those people would be a minority.

Filtering out the short activities is also a good idea, but I think it wouldn't get too much use. I imagine myself using the app and thinking I might want to enter an activity that lasted a short period of time (like 5 seconds) and disabling it outright. In addition to that, it would be extremely frustrating to accidentally select an activity and then have the time run out before the user can react.

My first instinct when I downloaded the app was to go to the diary and long-tap on the activity I wanted to remove, and sure enough, the message popped up telling me editing wasn't implemented yet. I feel like that long tap is the most obvious way to go about doing this, although it could be a separate button to switch to a edit mode. Again, I'm not sure if these ideas are in line with the principles and use cases of this app.

**Comment by ramack** [comment]
In the meantime I think the snackbar with an "UNDO" button is the best choice to handle accidental selections. Changing the history using in general is to be handled via #28.
